# Generated by Django 5.0.6 on 2024-06-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apna', '0002_contact_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=30)),
                ('item_price', models.FloatField(max_length=30)),
                ('item_brand', models.CharField(max_length=30)),
                ('item_category', models.CharField(max_length=30)),
            ],
        ),
    ]
