# Generated by Django 5.0.6 on 2024-06-21 08:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apna', '0003_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='item_image',
            field=models.ImageField(default='mixture.png', upload_to='product/'),
        ),
        migrations.AlterField(
            model_name='product',
            name='item_category',
            field=models.CharField(choices=[('S', 'SWEET'), ('N', 'NAMKEEN'), ('M', 'MEALS'), ('B', 'BAKERY')], max_length=1),
        ),
    ]
