# Generated by Django 5.0.6 on 2024-06-22 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Apna', '0005_cart'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='item_brand',
            field=models.CharField(choices=[('J', 'JHULELAL'), ('A', 'APNASWEET'), ('S', 'SAFFRON'), ('M', 'MISHRI')], max_length=1),
        ),
    ]
