# Generated by Django 5.0.6 on 2024-07-06 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Apna', '0010_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
    ]
